# Generated by Django 3.2.17 on 2023-02-06 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0004_auto_20230203_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='pikmessageexception',
            name='body_hash',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='sha1'),
        ),
    ]
