# Generated by Django 3.2.17 on 2023-02-09 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0005_pikmessageexception_body_hash'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pikmessageexception',
            unique_together={('queue', 'entity_uid'), ('queue', 'body_hash')},
        ),
    ]
