# Generated by Django 3.2.18 on 2023-07-05 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0006_alter_pikmessageexception_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pikmessageexception',
            name='entity_uid',
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name='Идентификатор сущности'),
        ),
        migrations.AddIndex(
            model_name='pikmessageexception',
            index=models.Index(fields=['entity_uid'], name='bus_pikmess_entity__b1ed12_idx'),
        ),
    ]
